### Read
GET http://localhost:8888/project_didy_mvc/project_spa/api/services/read.php HTTP/1.1

### Create
POST http://localhost:8888/project_didy_mvc/project_spa/api/services/create.php HTTP/1.1
content-type: application/json

{
    "service_name": "ทดสอบระบบ ServiceName",
    "description": "ทดสอบระบบ Description",
    "duration": 129,
    "price": 45
}

### Update
PUT  http://localhost:8888/project_didy_mvc/project_spa/api/services/update.php HTTP/1.1
content-type: application/json

{
    "service_name": "7777",
    "description": "8888",
    "duration": 129,
    "price": 45,
    "edit_id":1
}

### Update
DELETE  http://localhost:8888/project_didy_mvc/project_spa/api/services/delete.php HTTP/1.1 HTTP/1.1
content-type: application/json

{
    "id":3
}